services:
  dev:
    image: docker-next-js-dev
    build: .
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./src:/front/src

  server:
    depends_on:
      - mysql
    build: ../2203-wns-etchebest-virtuoz-back
    restart: always
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - 4000:4000
    container_name: server
    volumes:
      - ../2203-wns-etchebest-virtuoz-back/src/:/back/src/
      - ../2203-wns-etchebest-virtuoz-back/prisma/:/back/prisma/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    container_name: adminer

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    container_name: mysql
    healthcheck:
      test:
        ["CMD", "mysqladmin", "--password=prisma", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
