services:
  dev:
    image: docker-next-js-dev
    build: .
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./pages:/front/pages
      - ./public:/front/public
      - ./styles:/front/styles

  server:
    depends_on:
      - mysql
    build: ../backend-virtuoz
    restart: always
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - 4000:4000
    container_name: server
    volumes:
      - ../backend-virtuoz/src/:/back/src/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    container_name: adminer

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    container_name: mysql
    healthcheck:
      test:
        ["CMD", "mysqladmin", "--password=prisma", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
